label: 'hCNV Community'
tagline: 'Genomic Copy Number Variations in Humans'
description: |
  This is the website for the h-CNV community, originating in a project supported through ELIXIR's data communities initiative
keywords: CNV, genomics, genome variants, genome sequencing, genomic arrays
site_domain_name: hcnv.github.io
url: 'https://hcnv.github.io'

# The baseurl parameter is an empty string if the site is represented at the root
# of a domain. For project domains on Github it corresponds to the project name.
baseurl: ""

# the site_parent_link parameter is used e.g. for icon links.
site_parent_link: 'https://elixir-europe.org/about-us/implementation-studies/2019-hcnv'
github_organisation: hcnv

# instructions for processing specific directories
include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".
# The "_posts" collection is created by default.
collections:
  doc:
    output: true
    permalink: /doc/:path/
  people:
    output: true
    permalink: /people/:path/
  minutes:
    output: true
    permalink: /minutes/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout
nav_cat_blocks:     # comma-separated "label,type,label_visibility"
  standard: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

# content of the different navigation blocks
standard:
  about: 'About...'
  news: 'News & Events'
  people: Participants
  standards: 'Standards and Guidelines'
  resources: 'Resources & Databases'
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

related_sites:
  'h-CNV @ ELIXIR': 'https://elixir-europe.org/about-us/implementation-studies/2019-hcnv'
  'Beacon @ ELIXIR': 'http://www.elixir-europe.org/about-us/implementation-studies/beacons'
  'SchemaBlocks': 'http://schemablocks.org'

github_projects:
  'h-CNV': 'http://github.com/hcnv/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'
  'ELIXIR Beacon': 'http://github.com/ga4gh-beacon/'

# The categories-date-sorted parameter determines the selection of a
# time sorted, year labeled listing template for those categories.
categories-date-sorted:
  - news
  - minutes
  - events

tags-date-sorted:
  - press

# Only tags listed here are represented in the tag cloud.
cloud_tags:
  - Beacon
  - code
  - contacts
  - contributors
  - databases
  - documentation
  - developers
  - presentation
  - slides
  - standards
  - hackathon
  - FAQ
  - press
  - website

# additional Jekyll instructions
plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # displayed sidebar links in current category
emptyArray: []          # dummy element for array instantiation
